language: go
sudo: true

go:
  - 1.7.x
  - 1.8.x
  - master

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - sudo apt-get update
  - sudo apt-get -y install nodejs libxml2-utils
script:
  - make test
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=cover.out -service=travis-ci

